app1/urls.py
from django.urls import re_path, path
from .views import *

app_name = 'app1'

urlpatterns = [
    path('logout/', logout, name='logout'),
    path('', homepage, name='homepage'),
    path('dashboard/', dashboard, name='dashboard'),
    path('login/', login, name='login'),
    path('registerAdminSistem/', registerAdminSistem, name='registerAdminSistem'),
    path('editAdminSistem/', editAdminSistem, name='editAdminSistem'),
    path('registerPenggunaPublik/', registerPenggunaPublik, name='registerPenggunaPublik'),
    path('editPenggunaPublik/', editPenggunaPublik, name='editPenggunaPublik'),
    path('registerDokter/', registerDokter, name='registerDokter'),
    path('editDokter/', editDokter, name='editDokter'),
    path('registerAdminSatgas/', registerAdminSatgas, name='registerAdminSatgas'),
    path('editAdminSatgas/', editAdminSatgas, name='editAdminSatgas'),
    path('listPasien/', listPasien, name='listPasien'),
    path('daftarPasien/', daftarPasien, name='daftarPasien'),
    path('updatePasien/<str:idPasien>/<str:namaPasien>', updatePasien, name='updatePasien'),
    path('detailPasien/<str:idPasien>', detailPasien, name='detailPasien'),
    path('deletePasien/<str:idPasien>', deletePasien, name='deletePasien'),
]

app5/urls.py
from django.urls import re_path, path
from .views_transaksi_makan_dan_daftar_pesan import *
from .views_paket_makan import *
from .views_hotel import *

app_name = 'app5'

urlpatterns = [
    # transaksi makan dan daftar pesan
    path('createTransaksiMakan/', create_transaksi_makan, name='createTransaksiMakan'),
    path('listTransaksiMakan/', list_transaksi_makan, name='listTransaksiMakan'),
    path('deleteTransaksiMakan/', delete_transaksi_makan, name='deleteTransaksiMakan'),
    path('updateTransaksiMakan/', update_transaksi_makan, name='updateTransaksiMakan'),
    path('detailTransaksiMakan/', detail_transaksi_makan, name='detailTransaksiMakan'),
    path('api/getKodeHotelFromIdTransaksi', get_kode_hotel_from_id_transaksi, name="api_getKodeHotelFromIdTransaksi"),
    path('api/getKodePaketFromIdTransaksi', get_kode_paket_from_id_transaksi, name="api_getKodePaketFromIdTransaksi"),

    # paket makan
    path('createPaketMakan/', create_paket_makan, name='createPaketMakan'),
    path('listPaketMakan/', list_paket_makan, name='listPaketMakan'),
    path('deletePaketMakan/', delete_paket_makan, name='deletePaketMakan'),
    path('updatePaketMakan/', update_paket_makan, name='updatePaketMakan'),

    # hotel
    path('createHotel/', create_hotel, name='createHotel'),
    path('listHotel/', list_hotel, name='listHotel'),
    path('updateHotel/', update_hotel, name='updateHotel'),
]

tk4_kelompok8_basdat/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('app1.urls')),
    path('', include('app2.urls')),
    path('', include('app3.urls')),
    path('', include('app4.urls')),
    path('', include('app5.urls')),
]

app5/forms.py
from django import forms

class PaketMakanForm(forms.Form):
    kode_hotel_attrs = {
        'placeholder' : 'Kode Hotel',
        'class' : 'form-control',
        'required' : True,
        'maxlength': 5,
    }

    kode_paket_attrs = {
        'placeholder' : 'Kode Paket',
        'class' : 'form-control',
        'required' : True,
        'maxlength': 5,
    }
    
    nama_attrs = {
        'placeholder' : 'Nama',
        'class' : 'form-control',
        'required' : True,
        'maxlength': 20,
    }
    
    harga_attrs = {
        'type': 'number',
        'min': 0,
        'placeholder' : 'Harga',
        'class' : 'form-control',
        'required' : True,
    }

    kode_hotel = forms.CharField(widget=forms.TextInput(attrs=kode_hotel_attrs))
    kode_paket = forms.CharField(widget=forms.TextInput(attrs=kode_paket_attrs))
    nama = forms.CharField(widget=forms.TextInput(attrs=nama_attrs))
    harga = forms.IntegerField(widget=forms.TextInput(attrs=harga_attrs))

class HotelForm(forms.Form):
    nama_attrs = {
        'placeholder' : 'Nama',
        'class' : 'form-control',
        'required' : True,
        'maxlength': 30,
    }

    is_rujukan_attrs = {
        'class' : 'form-control',
        'required' : False,
    }

    jalan_attrs = {
        'placeholder' : 'Jalan',
        'class' : 'form-control',
        'required' : True,
        'maxlength': 30,
    }

    kelurahan_attrs = {
        'placeholder' : 'Kelurahan',
        'class' : 'form-control',
        'required' : True,
        'maxlength': 30,
    }

    kecamatan_attrs = {
        'placeholder' : 'Kecamatan',
        'class' : 'form-control',
        'required' : True,
        'maxlength': 30,
    }

    kabkot_attrs = {
        'placeholder' : 'Kabupaten / Kota',
        'class' : 'form-control',
        'required' : True,
        'maxlength': 30,
    }

    prov_attrs = {
        'placeholder' : 'Provinsi',
        'class' : 'form-control',
        'required' : True,
        'maxlength': 30,
    }

    nama = forms.CharField(widget=forms.TextInput(attrs=nama_attrs))
    is_rujukan = forms.BooleanField(widget=forms.CheckboxInput(attrs=is_rujukan_attrs), required=False)
    jalan = forms.CharField(widget=forms.TextInput(attrs=jalan_attrs))
    kelurahan = forms.CharField(widget=forms.TextInput(attrs=kelurahan_attrs))
    kecamatan = forms.CharField(widget=forms.TextInput(attrs=kecamatan_attrs))
    kabkot = forms.CharField(widget=forms.TextInput(attrs=kabkot_attrs))
    prov = forms.CharField(widget=forms.TextInput(attrs=prov_attrs))
    

app5/templates/app5/create_hotel.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> Buat Hotel </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="daftarPasien" class="p-4">
    <div class="daftarPasien">
        <div class="d-flex justify-content-center">
            <div class="card card-pasien">
                <div class="card-header">
                    <h3>Buat Hotel</h3>
                </div>
                <div class="card-body">
                    <form method="POST">
                        <div class="form-group">
                            {% csrf_token %}
                            {% if error %}
                            <p class="error">{{ error }}</p>
                            {% endif %}
                            <p>
                                <input type="hidden" name="kode_hotel" value="{{ kode_hotel }}">
                                <input class="form-control" value="Kode Hotel: {{ kode_hotel }}" disabled>
                            </p>
                            <div class="d-flex flex-column mr-auto">
                                <p>
                                    <b>Rujukan: </b>
                                    <input type="checkbox" name="is_rujukan" id="id_is_rujukan">
                                </p>
                            </div>
                            <p>
                                <input type="text" name="nama" placeholder="Nama" class="form-control" required maxlength="30" id="id_nama">
                            </p>
                            <p>
                                <input type="text" name="jalan" placeholder="Jalan" class="form-control" required maxlength="30" id="id_jalan">
                            </p>
                            <p>
                                <input type="text" name="kelurahan" placeholder="Kelurahan" class="form-control" required maxlength="30" id="id_kelurahan">
                            </p>
                            <p>
                                <input type="text" name="kecamatan" placeholder="Kecamatan" class="form-control" required maxlength="30" id="id_kecamatan">
                            </p>
                            <p>
                                <input type="text" name="kabkot" placeholder="Kabupaten / Kota" class="form-control" required maxlength="30" id="id_kabkot">
                            </p>
                            <p>
                                <input type="text" name="prov" placeholder="Provinsi" class="form-control" required maxlength="30" id="id_prov">
                            </p>
                        </div>
                        <button id="submit" class="btn btn-primary intabel" method="POST">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

app5/templates/app5/create_paket_makan.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> Buat Paket Makan </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="daftarPasien" class="p-4">
    <div class="daftarPasien">
        <div class="d-flex justify-content-center">
            <div class="card card-pasien">
                <div class="card-header">
                    <h3>Buat Paket Makan</h3>
                </div>
                <div class="card-body">
                    {% if error %}
                    <p class="error">{{ error }}</p>
                    {% endif %}
                    <form method="POST">
                        <div class="form-group">
                            {% csrf_token %}
                            <p>
                                <select name="kode_hotel" placeholder="Kode Hotel" class="form-control" required id="id_kode_hotel">
                                    <option value="" name="kode_hotel" disabled selected>Kode Hotel</option>
                                    {% for kode in kode_hotel %}
                                    <option value="{{ kode }}" name="kode_hotel">{{ kode }}</option>
                                    {% endfor %}
                                </select>
                            </p>
                            <p>
                                <input type="text" name="kode_paket" placeholder="Kode Paket" class="form-control" required maxlength="5" id="id_kode_paket">
                            </p>
                            <p>
                                <input type="text" name="nama" placeholder="Nama" class="form-control" required maxlength="20" id="id_nama">
                            </p>                            
                            <p>
                                <input type="number" name="harga" min="0" placeholder="Harga" class="form-control" required id="id_harga">
                            </p>
                        </div>
                        <button id="submit" class="btn btn-primary intabel" method="POST">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

app5/templates/app5/create_transaksi_makan.html
{% extends 'base.html' %}
{% load static %}
{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title>Buat Transaksi Makan</title>
{%endblock style%}

{% block content %}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="form-transaksi-makan" class="p-4">
    <div class="daftarPasien">
        <div class="d-flex justify-content-center">
            <div class="card card-pasien">
                <div class="card-header">
                    <h3>Buat Transaksi Makan</h3>
                </div>
                <div class="card-body">
                    <form method="POST">
                        <div class="form-group" id="form-group">
                            {% csrf_token %}
                            {% if error %}
                                <p class="error">{{ error }}</p>
                            {% endif %}
                            <p>
                                <select id="idTransaksi" onchange="onchangeIdTransaksi()" name="idTransaksi" class="form-control pasien" required="true" placeholder="Id Transaksi">
                                    <option value="" name="idTransaksi" disabled selected>--- Pilih Id Transaksi ---</option>
                                    {% for id in idTransaksi %}
                                    <option value="{{ id }}" name="idTransaksi">{{ id }}</option>
                                    {% endfor %}
                                 </select>
                            </p>
                            <p>
                                <input class="form-control pasien" required="true" placeholder="Id Transaksi Makan" value="Id Transaksi Makan: {{ idTransaksiMakan }}" disabled>
                                <input type="hidden" name="idTransaksiMakan" value="{{ idTransaksiMakan }}">
                            </p>
                            <p>
                                <input id="kodeHotel" class="form-control pasien" required="true" placeholder="Kode Hotel" disabled>
                                <input type="hidden" name="kodeHotel" id="kodeHotelHidden">
                            </p>
                        </div>
                        <button id="submit" class="btn btn-primary intabel" method="POST">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    var kodePaket = [];

    function onchangeIdTransaksi() {
        getKodeHotel();
        getKodePaketInit();
    }

    function getKodeHotel() {
        let xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                let res = JSON.parse(this.responseText);
                kodeHotel = document.getElementById('kodeHotel');
                kodeHotel.value = res['kodeHotel'];
                kodeHotel = document.getElementById('kodeHotelHidden');
                kodeHotel.value = res['kodeHotel'];
            }
        };
        idTransaksi = document.getElementById('idTransaksi').value;
        xhttp.open("GET", "{% url 'app5:api_getKodeHotelFromIdTransaksi' %}?idTransaksi=" + idTransaksi, true);
        xhttp.send();
    }

    function getKodePaketInit() {
        let xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                let res = JSON.parse(this.responseText);
                kodePaket = res['kodePaket'];
                cleanKodePaket();

                fg = document.getElementById('form-group');
                
                let added = document.createElement('h4');
                added.innerHTML = 'Pesanan:';
                fg.appendChild(added);

                let pAdded = document.createElement('p');
                fg.appendChild(pAdded);

                added = document.createElement('select');
                added.name = 'kodePaket';
                added.className = 'form-control pasien';
                added.required = 'true';
                added.placeholder = 'Kode Paket';
                pAdded.appendChild(added);

                let optionAdded = document.createElement('option');
                optionAdded.name = 'kodePaket';
                optionAdded.value = '';
                optionAdded.disabled = true;
                optionAdded.selected = true;
                optionAdded.innerHTML = '--- Pilih Kode Paket ---';
                added.appendChild(optionAdded);

                for (let i = 0; i < kodePaket.length; i++) {
                    optionAdded = document.createElement('option');
                    optionAdded.name = 'kodePaket';
                    optionAdded.value = kodePaket[i];
                    optionAdded.innerHTML = kodePaket[i];
                    added.appendChild(optionAdded);
                }

                added = document.createElement('button');
                added.type = 'button';
                added.className = 'btn btn-primary intabel';
                added.style = 'background-color: red;';
                added.innerHTML = 'Hapus Pesanan';
                added.onclick = function() { hapusPaket(this) };
                pAdded.appendChild(added);

                pAdded = document.createElement('p');
                fg.appendChild(pAdded);

                added = document.createElement('button');
                added.type = 'button';
                added.onclick = function() { getMoreKodePaket() };
                added.className = 'btn btn-primary intabel';
                added.innerHTML = 'Tambah Pesanan';
                pAdded.appendChild(added);
            }
        };
        idTransaksi = document.getElementById('idTransaksi').value;
        xhttp.open("GET", "{% url 'app5:api_getKodePaketFromIdTransaksi' %}?idTransaksi=" + idTransaksi, true);
        xhttp.send();
    }

    function getMoreKodePaket() {
        fg = document.getElementById('form-group');
        fg.removeChild(fg.children[fg.childElementCount - 1]);

        fg = document.getElementById('form-group');

        let pAdded = document.createElement('p');
        fg.appendChild(pAdded);

        added = document.createElement('select');
        added.name = 'kodePaket';
        added.className = 'form-control pasien';
        added.required = 'true';
        added.placeholder = 'Kode Paket';
        pAdded.appendChild(added);

        let optionAdded = document.createElement('option');
        optionAdded.name = 'kodePaket';
        optionAdded.value = '';
        optionAdded.disabled = true;
        optionAdded.selected = true;
        optionAdded.innerHTML = '--- Pilih Kode Paket ---';
        added.appendChild(optionAdded);

        for (let i = 0; i < kodePaket.length; i++) {
            optionAdded = document.createElement('option');
            optionAdded.name = 'kodePaket';
            optionAdded.value = kodePaket[i];
            optionAdded.innerHTML = kodePaket[i];
            added.appendChild(optionAdded);
        }

        added = document.createElement('button');
        added.type = 'button';
        added.className = 'btn btn-primary intabel';
        added.style = 'background-color: red;';
        added.innerHTML = 'Hapus Pesanan';
        added.onclick = function() { hapusPaket(this) };
        pAdded.appendChild(added);

        pAdded = document.createElement('p');
        fg.appendChild(pAdded);

        added = document.createElement('button');
        added.type = 'button';
        added.onclick = function() { getMoreKodePaket() };
        added.className = 'btn btn-primary intabel';
        added.innerHTML = 'Tambah Pesanan';
        pAdded.appendChild(added);
    }

    function cleanKodePaket() {
        fg = document.getElementById('form-group');
        while (fg.childElementCount > 4) {
            fg.removeChild(fg.children[4]);
        }
        nomorPaket = 0;
    }

    function hapusPaket(param) {
        fg = document.getElementById('form-group');
        if (fg.childElementCount == 7) {
            alert('Transaksi harus memiliki minimal satu paket');
            return;
        }
        let parent = param.parentElement;
        let parentOfParent = parent.parentElement;
        parentOfParent.removeChild(parent);
    }
</script>
{% endblock content %}

app5/templates/app5/error.html
{% extends 'base.html' %}
{% load static %}
{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title>Buat Transaksi Makan</title>
{%endblock style%}

{% block content %}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="error" class="p-4">
    <div class="listPasien">
        <div class="d-flex justify-content-center align-items-center">
            <p>Operasi tidak dapat dilakukan.</p>
        </div>
    </div>
</section>
{% endblock content %}

app5/templates/app5/list_paket_makan.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> List Paket Makan </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="listPasien" class="p-4">
    <div class="listPasien">
        <div class="d-flex justify-content-center align-items-center">
            <div class="card card-pasien">
                <div class="card-header">
                    <h3>List Paket Makan</h3>
                </div>
                <div class="card-body">
                <table class="table align-middle shadow p-3 mb-5 bg-white rounded">
                    <thead>
                      <tr>
                        <th scope="col">No.</th>
                        <th scope="col">Hotel</th>
                        <th scope="col">Kode Paket</th>
                        <th scope="col">Nama Paket</th>
                        <th scope="col">Harga</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for paket in paket_makan %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ paket.0 }}</td>
                            <td>{{ paket.1 }}</td>
                            <td>{{ paket.2 }}</td>
                            <td>Rp. {{ paket.3 }}</td>
                            {% if peran == 'admin' %}
                            <td>
                                <a href="{% url 'app5:updatePaketMakan' %}?kode_hotel={{ paket.0 }}&kode_paket={{ paket.1 }}"><button type="button" id="update" class="btn btn-secondary">Update</button></a>
                            </td>
                            {% if paket.4 == 0 %}
                            <td>
                                <form method="POST" action="{% url 'app5:deletePaketMakan' %}">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{ paket.0 }}" name="kode_hotel">
                                    <input type="hidden" value="{{ paket.1 }}" name="kode_paket">
                                    <button type="submit" id="delete" class="btn btn-secondary">Delete</button>
                                </form>
                            </td>
                            {% endif %}
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

app5/templates/app5/list_transaksi_makan.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> List Transaksi Makan </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="listPasien" class="p-4">
    <div class="listPasien">
        <div class="d-flex justify-content-center align-items-center">
            <div class="card card-pasien">
                <div class="card-header">
                    <h3>List Transaksi Makan</h3>
                </div>
                <div class="card-body">
                <table class="table align-middle shadow p-3 mb-5 bg-white rounded">
                    <thead>
                      <tr>
                        <th scope="col">No.</th>
                        <th scope="col">Id Transaksi Hotel</th>
                        <th scope="col">Id Transaksi</th>
                        <th scope="col">Total Bayar</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for transaksi in transaksiMakan %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ transaksi.0 }}</td>
                            <td>{{ transaksi.1 }}</td>
                            <td>Rp. {{ transaksi.2 }}</td>
                            {% if transaksi.3 != 'LUNAS' and peran == 'admin_satgas' %}
                            <td>
                                <a href="{% url 'app5:updateTransaksiMakan' %}?idTransaksi={{ transaksi.0 }}&idTransaksiMakan={{ transaksi.1 }}"><button type="button" id="update" class="btn btn-secondary">Update</button></a>
                            </td>
                            <td>
                                <form method="POST" action="{% url 'app5:deleteTransaksiMakan' %}">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{ transaksi.0 }}" name="idTransaksi">
                                    <input type="hidden" value="{{ transaksi.1 }}" name="idTransaksiMakan">
                                    <button type="submit" id="delete" class="btn btn-secondary">Delete</button>
                                </form>
                            </td>
                            {% endif %}
                            <td>
                                <a href="{% url 'app5:detailTransaksiMakan'%}?idTransaksi={{ transaksi.0 }}&idTransaksiMakan={{ transaksi.1 }}"><button type="button" id="detail" class="btn btn-secondary">Detail</button></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

app5/templates/app5/testing.html
HELLO

app5/templates/app5/update_hotel.html
{% extends 'base.html' %}
{% load static %}
{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title>Ubah Hotel</title>
{%endblock style%}

{% block content %}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section class="p-4">
    <div class="d-flex justify-content-center align-items-center">
        <div class="card card-pasien">
            <div class="card-header">
                <h3>Ubah Hotel</h3>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% if error %}
                        <p class="error">{{ error }}</p>
                    {% endif %}
                    <div class="form-group" id="form-group">
                        {% csrf_token %}
                        <input type="hidden" name="kode_hotel" value="{{ kode_hotel }}" required>
                        <div class="d-flex flex-column mr-auto">
                            <p><b>Kode Hotel: </b>{{ kode_hotel }}</p>
                            <p>
                                <b>Rujukan: </b>
                                {% if hotel.1 == '1' %}
                                <input type="checkbox" checked="checked" name="is_rujukan" id="id_is_rujukan">
                                {% else %}
                                <input type="checkbox" name="is_rujukan" id="id_is_rujukan">
                                {% endif %}
                            </p>
                        </div>
                        <p>
                            <input type="text" name="nama" placeholder="Nama" class="form-control" required maxlength="30" id="id_nama" value="{{ hotel.0 }}">
                        </p>
                        <p>
                            <input type="text" name="jalan" placeholder="Jalan" class="form-control" required maxlength="30" id="id_jalan" value="{{ hotel.2 }}">
                        </p
                        <p>
                            <input type="text" name="kelurahan" placeholder="Kelurahan" class="form-control" required maxlength="30" id="id_kelurahan" value="{{ hotel.3 }}">
                        </p>
                        <p>
                            <input type="text" name="kecamatan" placeholder="Kecamatan" class="form-control" required maxlength="30" id="id_kecamatan" value="{{ hotel.4 }}">
                        </p>
                        <p>
                            <input type="text" name="kabkot" placeholder="Kabupaten / Kota" class="form-control" required maxlength="30" id="id_kabkot" value="{{ hotel.5 }}">
                        </p>
                        <p>
                            <input type="text" name="prov" placeholder="Provinsi" class="form-control" required maxlength="30" id="id_prov" value="{{ hotel.6 }}">
                        </p>
                    </div>
                    <button id="submit" class="btn btn-primary intabel" method="POST">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

app5/templates/app5/update_paket_makan.html
{% extends 'base.html' %}
{% load static %}
{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title>Ubah Paket Makan</title>
{%endblock style%}

{% block content %}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section class="p-4">
    <div class="d-flex justify-content-center align-items-center">
        <div class="card card-pasien">
            <div class="card-header">
                <h3>Ubah Paket Makan</h3>
            </div>
            <div class="d-flex flex-column mr-auto">
                <div>
                    <p><b>Hotel: </b>{{ kode_hotel }}</p>
                </div>
                <div>
                    <p><b>Kode Paket: </b>{{ kode_paket }}</p>
                </div>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% if error %}
                        <p class="error">{{ error }}</p>
                    {% endif %}
                    <div class="form-group" id="form-group">
                        {% csrf_token %}
                        <input type="hidden" name="kode_hotel" value="{{ kode_hotel }}" required>
                        <input type="hidden" name="kode_paket" value="{{ kode_paket }}" required>
                        <p>
                            <input value="{{ paket_makan.0 }}" type="text" name="nama" placeholder="Nama" class="form-control" required maxlength="20" id="id_nama">
                        </p>                            
                        <p>
                            <input value="{{ paket_makan.1 }}" type="number" name="harga" min="0" placeholder="Harga" class="form-control" required id="id_harga">
                        </p>
                    </div>
                    <button id="submit" class="btn btn-primary intabel" method="POST">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}