app1/urls.py
from django.urls import re_path, path
from .views import *

app_name = 'app1'

urlpatterns = [
    path('logout/', logout, name='logout'),
    path('', homepage, name='homepage'),
    path('dashboard/', dashboard, name='dashboard'),
    path('login/', login, name='login'),
    path('registerAdminSistem/', registerAdminSistem, name='registerAdminSistem'),
    path('editAdminSistem/', editAdminSistem, name='editAdminSistem'),
    path('registerPenggunaPublik/', registerPenggunaPublik, name='registerPenggunaPublik'),
    path('editPenggunaPublik/', editPenggunaPublik, name='editPenggunaPublik'),
    path('registerDokter/', registerDokter, name='registerDokter'),
    path('editDokter/', editDokter, name='editDokter'),
    path('registerAdminSatgas/', registerAdminSatgas, name='registerAdminSatgas'),
    path('editAdminSatgas/', editAdminSatgas, name='editAdminSatgas'),
    path('listPasien/', listPasien, name='listPasien'),
    path('daftarPasien/', daftarPasien, name='daftarPasien'),
    path('updatePasien/<str:idPasien>/<str:namaPasien>', updatePasien, name='updatePasien'),
    path('detailPasien/<str:idPasien>', detailPasien, name='detailPasien'),
    path('deletePasien/<str:idPasien>', deletePasien, name='deletePasien'),
]

app2/urls.py
from django.urls import re_path, path
from .views import *

app_name = 'app2'

urlpatterns = [
    path('listJadwalDokter/', listJadwalDokter, name='listJadwalDokter'),
    path('buatJadwalDokter/', buatJadwalDokter, name='buatJadwalDokter'),
    path('tambahJadwalDokter/<str:kodeFaskes>/<str:shift>/<str:tanggal>', tambahJadwalDokter, name='tambahJadwalDokter'),
    path('buatAppointmentDenganDokter/', buatAppointmentDenganDokter, name='buatAppointmentDenganDokter'),
    path('tambahAppointmentDenganDokter/<str:noSTR>/<str:email>/<str:kodeFaskes>/<str:shift>/<str:tanggal>/', tambahAppointmentDenganDokter, name='tambahAppointmentDenganDokter'),
    path('listAppointmentDenganDokter/', listAppointmentDenganDokter, name='listAppointmentDenganDokter'),
    path('updateAppointmentDenganDokter/<str:nik>/<str:noSTR>/<str:email>/<str:kodeFaskes>/<str:shift>/<str:tanggal>/', updateAppointmentDenganDokter, name='updateAppointmentDenganDokter'),
    path('deleteAppointmentDenganDokter/<str:nik>/<str:noSTR>/<str:email>/<str:kodeFaskes>/<str:shift>/<str:tanggal>/', deleteAppointmentDenganDokter, name='deleteAppointmentDenganDokter'),
    path('buatRuanganRS/', buatRuanganRS, name='buatRuanganRS'),
    path('dataKodeRuangan/', dataKodeRuangan, name='dataKodeRuangan'),
    path('listRuanganRS/', listRuanganRS, name='listRuanganRS'),
    path('updateRuanganRS/<str:kodeRS>/<str:kodeRuangan>/', updateRuanganRS, name='updateRuanganRS'),
    path('buatBedRS/', buatBedRS, name='buatBedRS'),
    path('jsonKodeRuangan/', jsonKodeRuangan, name='jsonKodeRuangan'),
    path('listBedRS/', listBedRS, name='listBedRS'),
    path('deleteBedRS/<str:kodeRS>/<str:kodeRuangan>/<str:kodeBed>/', deleteBedRS, name='deleteBedRS'),
]

tk4_kelompok8_basdat/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('app1.urls')),
    path('', include('app2.urls')),
    path('', include('app3.urls')),
    path('', include('app4.urls')),
    path('', include('app5.urls')),
]

app2/views.py
from django.shortcuts import render, redirect
from django.db import connection
from django.http import JsonResponse
from django.shortcuts import render
from .forms import *
from datetime import datetime
from django import forms

url_dashboard = 'app1:dashboard'
url_login = 'app1:login'
url_listPasien = 'app1:listPasien'

def set_username(request, response):
    response['is_authenticated'] = request.session.get('is_authenticated')
    response['username'] = request.session.get('username')
    response['peran'] = request.session.get('peran')

def listJadwalDokter(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_login)
    response = {}
    set_username(request, response)
    stmt1 = '''
    SELECT * FROM jadwal_dokter WHERE username='{0}'
    '''.format(response['username'])
    stmt2 = '''
    SELECT * FROM jadwal_dokter
    '''
    if(response['peran'] == 'dokter'):
        try:
            jadwal = tuple()
            with connection.cursor() as cursor:
                cursor.execute(stmt1)
                jadwal = cursor.fetchall()
            newJadwal = [(a[0], a[1], a[2], a[3], a[4].strftime('%Y-%m-%d'), a[5]) for a in jadwal]
            response['jadwal'] = newJadwal
        except Exception as e:
            e = str(e)
            print(e)
    if(response["peran"] == 'pengguna_publik' or response["peran"] == 'admin_satgas'):
        try:
            jadwal = tuple()
            with connection.cursor() as cursor:
                cursor.execute(stmt2)
                jadwal = cursor.fetchall()
            newJadwal = [(a[0], a[1], a[2], a[3], a[4].strftime('%Y-%m-%d'), a[5]) for a in jadwal]
            response['jadwal'] = newJadwal
        except Exception as e:
            e = str(e)
            print(e)
    return render(request, 'app2/listJadwalDokter.html', response)

def buatJadwalDokter(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_login)
    response = {}
    set_username(request, response)
    stmt1 = '''
    SELECT kode_faskes, shift, tanggal FROM jadwal EXCEPT SELECT J.kode_faskes, J.shift, J.tanggal FROM jadwal J, jadwal_dokter JD WHERE J.kode_faskes = JD.kode_faskes AND J.shift = JD.shift AND J.tanggal = JD.tanggal AND JD.username = '{0}';
    '''.format(response['username'])
    if(response['peran'] == 'dokter'):
        try:
            jadwal = tuple()
            with connection.cursor() as cursor:
                cursor.execute(stmt1)
                jadwal = cursor.fetchall()
            newJadwal = [(a[0], a[1], a[2].strftime('%Y-%m-%d')) for a in jadwal]
            response['jadwal'] = newJadwal
        except Exception as e:
            e = str(e)
            print(e)
    return render(request, 'app2/buatJadwalDokter.html', response)

def tambahJadwalDokter(request, kodeFaskes, shift, tanggal):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_login)
    response = {}
    set_username(request, response)
    tanggal = datetime.strptime(tanggal, '%Y-%m-%d').date()
    jmlpasien = 0
    stmt1 = '''
    SELECT noSTR from dokter where username = '{0}'
    '''.format(response['username'])
    stmt2 = '''
    INSERT INTO jadwal_dokter(nostr, username, kode_faskes, shift, tanggal, jmlpasien) VALUES (%s, %s, %s, %s, %s, %s);
    '''
    if(response['peran'] == 'dokter'):
        try:
            with connection.cursor() as cursor:
                cursor.execute(stmt1)
                noSTR = cursor.fetchone()[0]
            with connection.cursor() as cursor:
                cursor.execute(stmt2, [noSTR, response['username'], kodeFaskes, shift, tanggal, jmlpasien])
                connection.commit()
            return redirect('app2:buatJadwalDokter')
        except Exception as e:
            e = str(e)
            print(e)
    return render(request, 'app2/buatJadwalDokter.html', response)

def buatAppointmentDenganDokter(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_login)
    response = {}
    set_username(request, response)
    stmt1 = '''
    SELECT * FROM jadwal_dokter;
    '''
    if(response['peran'] == 'pengguna_publik' or response['peran'] == 'admin_satgas'):
        try:
            jadwal = tuple()
            with connection.cursor() as cursor:
                cursor.execute(stmt1)
                jadwal = cursor.fetchall()
            newJadwal = [(a[0], a[1], a[2], a[3], a[4].strftime('%Y-%m-%d'), a[5]) for a in jadwal]
            response['jadwal'] = newJadwal
        except Exception as e:
            e = str(e)
            print(e)
    return render(request, 'app2/buatAppointmentDenganDokter.html', response)

def tambahAppointmentDenganDokter(request, noSTR, email, kodeFaskes, shift, tanggal):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_login)
    response = {}
    set_username(request, response)
    tanggal = datetime.strptime(tanggal, '%Y-%m-%d').date()
    if (request.method == 'POST'):
        isian = request.POST.copy()
        isian['email'] = email
        isian['kodeFaskes'] = kodeFaskes
        isian['shift'] = shift
        isian['tanggal'] = tanggal
        form = AppointmentDokterForm(isian)
        if(form.is_valid()):
            stmt1 = '''
            INSERT INTO memeriksa(nik_pasien, nostr, username_dokter, kode_faskes, praktek_shift, tgl_periksa) VALUES (%s,%s,%s,%s,%s,%s);
            '''
            if(response['peran'] == 'pengguna_publik' or response['peran'] == 'admin_satgas'):
                try:
                    with connection.cursor() as cursor:
                        cursor.execute(stmt1, [form.cleaned_data['nik'], noSTR, email, kodeFaskes, shift, tanggal])
                        connection.commit()
                    return redirect(url_dashboard)
                except Exception as e:
                    e = str(e)
                    print(e)
                    if ('duplicate key value violates unique constraint "memeriksa_pkey"' in e):
                        response['error'] = 'Pasien tidak bisa dibuatkan appointment karena telah terdaftar.'
                    elif('Jadwal dokter ini sudah penuh.') :
                        response['error'] = 'Jadwal dokter ini sudah penuh.'
                    else:
                        response['error'] = 'Terdapat sebuah kesalahan, silahkan coba lagi.'

    appointmentDokterForm = AppointmentDokterForm(request.POST)
    appointmentDokterForm.fields['nik'].widget.choices = get_list_nik(response['username'], response['peran'])
    appointmentDokterForm.fields['email'].widget.attrs['value'] = 'Email: ' + email
    appointmentDokterForm.fields['kodeFaskes'].widget.attrs['value'] = 'Kode Faskes: ' + kodeFaskes
    appointmentDokterForm.fields['shift'].widget.attrs['value'] = 'Shift: ' + shift
    appointmentDokterForm.fields['tanggal'].widget.attrs['value'] = 'Tanggal: ' + tanggal.strftime('%Y-%m-%d')
    response['form'] = appointmentDokterForm
    return render(request, 'app2/tambahAppointmentDenganDokter.html', response)

def get_list_nik(username, peran):
    if(peran == 'pengguna_publik'):
        stmt = '''
        SELECT nik FROM pasien WHERE idpendaftar='{0}';
        '''.format(username)
    elif (peran == 'admin_satgas'):
        stmt = '''
        SELECT nik FROM pasien;
        '''
    else:
        return []

    nik = tuple()
    try:
        with connection.cursor() as cursor:
            cursor.execute(stmt)
            nik = cursor.fetchall()
    except:
        pass
    return [('NIK Pasien', 'NIK Pasien')] + [(nikPasien[0], nikPasien[0]) for nikPasien in nik]

def listAppointmentDenganDokter(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_login)
    response = {}
    set_username(request, response)
    stmt1 = '''
    SELECT nik_pasien, nostr, username_dokter, kode_faskes, praktek_shift, tgl_periksa, rekomendasi FROM memeriksa, pasien WHERE nik = nik_pasien AND idpendaftar='{0}';
    '''.format(response['username'])
    stmt2 = '''
    SELECT nik_pasien, nostr, username_dokter, kode_faskes, praktek_shift, tgl_periksa, rekomendasi FROM memeriksa;
    '''
    stmt3 = '''
    SELECT nik_pasien, nostr, username_dokter, kode_faskes, praktek_shift, tgl_periksa, rekomendasi FROM memeriksa WHERE username_dokter='{0}';
    '''.format(response['username'])

    try:
        jadwal = tuple()
        if(response['peran'] == 'pengguna_publik'):
            with connection.cursor() as cursor:
                cursor.execute(stmt1)
                jadwal = cursor.fetchall()
            newJadwal = [(a[0], a[1], a[2], a[3], a[4], a[5].strftime('%Y-%m-%d'), a[6]) for a in jadwal]
            response['jadwal'] = newJadwal

        elif(response['peran'] == 'admin_satgas'):
            with connection.cursor() as cursor:
                cursor.execute(stmt2)
                jadwal = cursor.fetchall()
            newJadwal = [(a[0], a[1], a[2], a[3], a[4], a[5].strftime('%Y-%m-%d'), a[6]) for a in jadwal]
            response['jadwal'] = newJadwal

        elif(response['peran'] == 'dokter'):
            with connection.cursor() as cursor:
                cursor.execute(stmt3)
                jadwal = cursor.fetchall()
            newJadwal = [(a[0], a[1], a[2], a[3], a[4], a[5].strftime('%Y-%m-%d'), a[6]) for a in jadwal]
            response['jadwal'] = newJadwal
    except Exception as e:
        e = str(e)
        print(e)
    return render(request, 'app2/listAppointmentDenganDokter.html', response)

def updateAppointmentDenganDokter(request, nik, noSTR, email, kodeFaskes, shift, tanggal):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_login)
    response = {}
    set_username(request, response)
    tanggal = datetime.strptime(tanggal, '%Y-%m-%d').date()
    if (request.method == 'POST'):
        isian = request.POST.copy()
        isian['nik'] = nik
        isian['email'] = email

app2/templates/app2/buatAppointmentDenganDokter.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> Daftar Pasien </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="buatAppointmentDokter" class="p-4">
    <div class="buatAppointmentDokter">
      {% if peran == 'pengguna_publik' or peran == 'admin_satgas' %}
      <h3>Form Pembuatan Appointment Dengan Dokter</h3>
        <div class="d-flex justify-content-center align-items-center">
            <table class="table align-middle shadow p-3 mb-5 bg-white rounded">
                <thead>
                  <tr>
                    <th scope="col">No.</th>
                    <th scope="col">No STR</th>
                    <th scope="col">Email Dokter</th>
                    <th scope="col">Kode Faskes</th>
                    <th scope="col">Shift</th>
                    <th scope="col">Tanggal</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                    {%for nostr, username, kode_faskes, shift, tanggal, jmlpasien in jadwal%}
                  <tr>
                    <td> {{nostr}} </td>
                    <td> {{username}} </td>
                    <td> {{kode_faskes}} </td>
                    <td> {{shift}} </td>
                    <td> {{tanggal}} </td>
                    <td>
                        <a href="{% url 'app2:tambahAppointmentDenganDokter' noSTR=nostr email=username kodeFaskes=kode_faskes shift=shift tanggal=tanggal %}">
                        <button type="button" id="update" class="btn btn-secondary" method="POST">Book</button>
                      </td>
                  </tr>
                  {%endfor%}
                  <script>
                    var tables = document.getElementsByTagName('tbody')
                    var table = tables[tables.length - 1];
                    var rows = table.rows;
                    for(var i = 0, td; i < rows.length; i++){
                        td = document.createElement('td');
                        td.appendChild(document.createTextNode(i + 1));
                        rows[i].insertBefore(td, rows[i].firstChild);
                    }
                </script>
                </tbody>
              </table>
        </div>
        {% if peran == 'pengguna_publik' or peran == 'admin_satgas' %}
        <a href="{% url 'app2:listAppointmentDenganDokter' %}"> 
            <button type="button" id="jadwal-dokter" class="btn btn-secondary">Cek Appointment Dengan Dokter</button>
        </a>
        {% endif %}
        {% else %}
        <div class="card-header">
          <h3>Anda tidak dapat mengakses halaman ini</h3>
        </div>
        {% endif %}
    </div>
</section>
{% endblock content %}

app2/templates/app2/buatBedRS.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> Daftar Pasien </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="buatBedRS" class="p-4">
    <div class="buatBedRS">
        <div class="d-flex justify-content-center align-items-center">
            {% if peran == 'admin_satgas' %}
            <div class="card-body">
                <h3>Form Pembuatan Bed Rumah Sakit</h3>
                <form method="POST" id="BedRS" bed-rs-url="{% url 'app2:jsonKodeRuangan' %}">
                    <div class="form-group">
                        {% csrf_token %}
                        {%for field in form%}
                            <p> {{field}} </p>
                        {%endfor%}
                    </div>
                    <button id="submit" class="btn btn-primary intabel" method="POST">Simpan</button>
                </form>
            </div>
        </div>
        {% else %}
        <div class="card-header">
          <h3>Anda tidak dapat mengakses halaman ini</h3>
        </div>
        {% endif %}
    </div>
</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'app2/javascript/app2.js' %}" type="text/javascript"></script>
{% endblock content %}

app2/templates/app2/buatJadwalDokter.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> Daftar Pasien </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="buatJadwalDokter" class="p-4">
    <div class="buatJadwalDokter">
      {% if 'dokter' == peran %}
        <h3>Form Pembuatan Jadwal Dokter</h3>
        <div class="d-flex justify-content-center align-items-center">
            <table class="table align-middle shadow p-3 mb-5 bg-white rounded">
                <thead>
                  <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Kode Faskes</th>
                    <th scope="col">Shift</th>
                    <th scope="col">Tanggal</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                    {%for kode_faskes,shift,tanggal in jadwal%}
                  <tr>
                    <td> {{kode_faskes}} </td>
                    <td> {{shift}} </td>
                    <td> {{tanggal}} </td>
                    <td>
                        <a href="{% url 'app2:tambahJadwalDokter' kodeFaskes=kode_faskes shift=shift tanggal=tanggal %}">
                        <button type="button" id="update" class="btn btn-secondary">Create</button>
                      </td>
                  </tr>
                  {%endfor%}
                  <script>
                    var tables = document.getElementsByTagName('tbody')
                    var table = tables[tables.length - 1];
                    var rows = table.rows;
                    for(var i = 0, td; i < rows.length; i++){
                        td = document.createElement('td');
                        td.appendChild(document.createTextNode(i + 1));
                        rows[i].insertBefore(td, rows[i].firstChild);
                    }
                </script>
                </tbody>
              </table>
        </div>
        {% else %}
        <div class="card-header">
          <h3>Anda tidak dapat mengakses halaman ini</h3>
        </div>
        {% endif %}
    </div>
</section>
{% endblock content %}

app2/templates/app2/listAppointmentDenganDokter.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> Daftar Pasien </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="listJadwalDokter" class="p-4">
    <div class="listJadwalDokter">
      {% if peran == 'pengguna_publik' or peran == 'dokter' or peran == 'admin_satgas' %}
      <h3>List Appointment Dengan Dokter</h3>
        <div class="d-flex justify-content-center align-items-center">
            <table class="table align-middle shadow p-3 mb-5 bg-white rounded">
                <thead>
                  <tr>
                    <th scope="col">No.</th>
                    <th scope="col">NIK Pasien</th>
                    <th scope="col">Email Dokter</th>
                    <th scope="col">Faskes</th>
                    <th scope="col">Shift</th>
                    <th scope="col">Tanggal</th>
                    <th scope="col">Rekomendasi</th>
                    {% if peran == 'dokter' or peran == 'admin_satgas' %}
                    <th scoper="col">Action</th>
                    {% endif %}
                  </tr>
                </thead>
                <tbody>
                    {%for NIK,nostr,Email,kodeFaskes,shift,tanggal,rekomendasi in jadwal%}
                  <tr>
                    <td> {{NIK}} </td>
                    <td> {{Email}} </td>
                    <td> {{kodeFaskes}} </td>
                    <td> {{shift}} </td>
                    <td> {{tanggal}} </td>
                    <td> {{rekomendasi}} </td>
                    {% if peran == 'dokter' %}
                    <td>
                      <a href="{% url 'app2:updateAppointmentDenganDokter' nik=NIK noSTR=nostr email=Email kodeFaskes=kodeFaskes shift=shift tanggal=tanggal %}">
                      <button type="button" id="update" class="btn btn-secondary">Update</button>
                    </td>
                    {% endif %}
                    {% if peran == 'admin_satgas' %}
                    <td>
                      <a href="{% url 'app2:deleteAppointmentDenganDokter' nik=NIK noSTR=nostr email=Email kodeFaskes=kodeFaskes shift=shift tanggal=tanggal %}">
                      <button type="button" id="delete" class="btn btn-secondary">Delete</button>
                    </td>
                    {% endif %}
                  </tr>
                  {%endfor%}
                  <script>
                    var tables = document.getElementsByTagName('tbody')
                    var table = tables[tables.length - 1];
                    var rows = table.rows;
                    for(var i = 0, td; i < rows.length; i++){
                        td = document.createElement('td');
                        td.appendChild(document.createTextNode(i + 1));
                        rows[i].insertBefore(td, rows[i].firstChild);
                    }
                </script>
                </tbody>
              </table>
        </div>
        {% if peran == 'pengguna_publik' or peran == 'admin_satgas' %}
        <a href="{% url 'app2:buatAppointmentDenganDokter' %}"> 
            <button type="button" id="jadwal-dokter" class="btn btn-secondary">Buat Appointment Dengan Dokter</button>
        </a>
        {% endif %}
        {% else %}
        <div class="card-header">
          <h3>Anda tidak dapat mengakses halaman ini</h3>
        </div>
        {% endif %}
    </div>
</section>
{% endblock content %}

app2/templates/app2/listBedRS.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> Daftar Pasien </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="listJadwalDokter" class="p-4">
    <div class="listJadwalDokter">
      <h3>List Bed Ruangan RS</h3>
        <div class="d-flex justify-content-center align-items-center">
            {% if peran == 'admin_satgas' %}
            <table class="table align-middle shadow p-3 mb-5 bg-white rounded">
                <thead>
                  <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Kode RS</th>
                    <th scope="col">Kode Ruangan</th>
                    <th scope="col">Kode Bed</th>
                    <th scoper="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                    {%for kodeRuangan, kodeRS, kodeBed in bedRS%}
                  <tr>
                    <td> {{kodeRS}} </td>
                    <td> {{kodeRuangan}} </td>
                    <td> {{kodeBed}} </td>
                    <td>
                      <a href="{% url 'app2:deleteBedRS' kodeRS kodeRuangan kodeBed %}">
                      <button type="button" id="delete" class="btn btn-secondary">Delete</button>
                    </td>
                  </tr>
                  {%endfor%}
                  <script>
                    var tables = document.getElementsByTagName('tbody')
                    var table = tables[tables.length - 1];
                    var rows = table.rows;
                    for(var i = 0, td; i < rows.length; i++){
                        td = document.createElement('td');
                        td.appendChild(document.createTextNode(i + 1));
                        rows[i].insertBefore(td, rows[i].firstChild);
                    }
                </script>
                </tbody>
              </table>
        </div>
        {% else %}
        <div class="card-header">
          <h3>Anda tidak dapat mengakses halaman ini</h3>
        </div>
        {% endif %}
    </div>
</section>
{% endblock content %}

app2/templates/app2/listRuanganRS.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> Daftar Pasien </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="listJadwalDokter" class="p-4">
    <div class="listJadwalDokter">
      {% if peran == 'admin_satgas' %}
      <h3>List Ruangan Rumah Sakit</h3>
        <div class="d-flex justify-content-center align-items-center">
            <table class="table align-middle shadow p-3 mb-5 bg-white rounded">
                <thead>
                  <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Kode RS</th>
                    <th scope="col">Kode Ruangan</th>
                    <th scope="col">Tipe</th>
                    <th scope="col">Jumlah Bed</th>
                    <th scope="col">Harga</th>
                    <th scoper="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                    {%for kodeRS, kodeRuangan, tipe, jmlbed, harga in ruanganRS%}
                  <tr>
                    <td> {{kodeRS}} </td>
                    <td> {{kodeRuangan}} </td>
                    <td> {{tipe}} </td>
                    <td> {{jmlbed}} </td>
                    <td> {{harga}} </td>
                    <td>
                      <a href="{% url 'app2:updateRuanganRS' kodeRS kodeRuangan %}">
                      <button type="button" id="update" class="btn btn-secondary">Update</button>
                    </td>
                  </tr>
                  {%endfor%}
                  <script>
                    var tables = document.getElementsByTagName('tbody')
                    var table = tables[tables.length - 1];
                    var rows = table.rows;
                    for(var i = 0, td; i < rows.length; i++){
                        td = document.createElement('td');
                        td.appendChild(document.createTextNode(i + 1));
                        rows[i].insertBefore(td, rows[i].firstChild);
                    }
                </script>
                </tbody>
              </table>
        </div>
        {% else %}
        <div class="card-header">
          <h3>Anda tidak dapat mengakses halaman ini</h3>
        </div>
        {% endif %}
    </div>
</section>
{% endblock content %}