app1/urls.py
from django.urls import re_path, path
from .views import *

app_name = 'app1'

urlpatterns = [
    path('logout/', logout, name='logout'),
    path('', homepage, name='homepage'),
    path('dashboard/', dashboard, name='dashboard'),
    path('login/', login, name='login'),
    path('registerAdminSistem/', registerAdminSistem, name='registerAdminSistem'),
    path('editAdminSistem/', editAdminSistem, name='editAdminSistem'),
    path('registerPenggunaPublik/', registerPenggunaPublik, name='registerPenggunaPublik'),
    path('editPenggunaPublik/', editPenggunaPublik, name='editPenggunaPublik'),
    path('registerDokter/', registerDokter, name='registerDokter'),
    path('editDokter/', editDokter, name='editDokter'),
    path('registerAdminSatgas/', registerAdminSatgas, name='registerAdminSatgas'),
    path('editAdminSatgas/', editAdminSatgas, name='editAdminSatgas'),
    path('listPasien/', listPasien, name='listPasien'),
    path('daftarPasien/', daftarPasien, name='daftarPasien'),
    path('updatePasien/<str:idPasien>/<str:namaPasien>', updatePasien, name='updatePasien'),
    path('detailPasien/<str:idPasien>', detailPasien, name='detailPasien'),
    path('deletePasien/<str:idPasien>', deletePasien, name='deletePasien'),
]

app3/urls.py
from django.urls import re_path, path
from .views import *

app_name = 'app3'

urlpatterns = [
    path('reservasiRS/', reservasiRS, name='reservasiRS'),
    path('data/BasedOnKodeRS/', data_basedOnKodeRS, name='data_basedOnKodeRS'),
    path('listReservasiRS/', listReservasiRS, name='listReservasiRS'),
    path('updateReservasiRS/<str:kodepasien>/<str:tglMasuk>/', updateReservasiRS, name='updateReservasiRS'),
    path('submitUpdateReservasiRS/', submitUpdateReservasiRS, name='submitUpdateReservasiRS'),
    path('deleteReservasiRS/<str:kodepasien>/<str:tglMasuk>/', deleteReservasiRS, name='deleteReservasiRS'),

    path('buatJadwalFaskes/', buatJadwalFaskes, name='buatJadwalFaskes'),
    path('listJadwalFaskes/', listJadwalFaskes, name='listJadwalFaskes'),

    path('buatRS/', buatRS, name='buatRS'),
    path('listRumahSakit/', listRumahSakit, name='listRumahSakit'),
    path('updateRS/<str:kode_faskes>/', updateRS, name='updateRS'),
    path('submitUpdateRS/', submitUpdateRS, name='submitUpdateRS'),

    path('listTransaksiRS/', listTransaksiRS, name='listTransaksiRS'),
    path('updateTransaksiRS/<str:id_transaksi>/', updateTransaksiRS, name='updateTransaksiRS'),
    path('submitTransaksiRS/', submitTransaksiRS, name='submitTransaksiRS'),
    path('deleteTransaksiRS/<str:id_transaksi>/', deleteTransaksiRS, name='deleteTransaksiRS'),

    path('buatFaskes/', buatFaskes, name='buatFaskes'),
    path('listFaskes/', listFaskes, name='listFaskes'),
    path('updateFaskes/<str:kode>/', updateFaskes, name='updateFaskes'),
    path('submitFaskes/', submitFaskes, name='submitFaskes'),
    path('deleteFaskes/<str:kode>/', deleteFaskes, name='deleteFaskes'),
    path('detailFaskes/<str:kode>/', detailFaskes, name='detailFaskes'),
]

tk4_kelompok8_basdat/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('app1.urls')),
    path('', include('app2.urls')),
    path('', include('app3.urls')),
    path('', include('app4.urls')),
    path('', include('app5.urls')),
]

app3/views.py
from django.shortcuts import render, redirect
from django.db import connection
from django.shortcuts import render
from .forms import *
from django.http import JsonResponse
from app1.views import *
import pandas as pd
import datetime as datetime

# RESERVASI RS
def reservasiRS(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_login)
    response = {}
    set_username(request, response)

    if (request.session.get('peran') not in ["admin_satgas"]):
        response["peran_diizinkan"] = ["Admin Satgas"]
        return render(request, "app3/error.html", response)

    if ((request.method == 'POST')):
        form = ReservasiRSForm(request.POST)
        
        if (form.is_valid()):
            stmt1 = '''
            INSERT INTO reservasi_rs(kodepasien, tglMasuk, tglKeluar, koders, koderuangan, kodebed) VALUES (%s,%s,%s,%s,%s,%s);
            '''
            kodePasien = request.POST.get('nik')
            tglMasuk = form.cleaned_data['tglMasuk']
            tglKeluar = form.cleaned_data['tglKeluar']
            koders = request.POST.get('kode_RS')
            koderuangan = form.cleaned_data['kode_ruangan']
            kodebed = form.cleaned_data['kode_bed']

            tglMasuk = pd.to_datetime(tglMasuk)
            tglKeluar = pd.to_datetime(tglKeluar)

            if (tglMasuk > tglKeluar):
                return redirect('/reservasiRS/')

            else :
                try:
                    with connection.cursor() as cursor:
                        cursor.execute(stmt1, [kodePasien, tglMasuk, tglKeluar, koders, koderuangan, kodebed])
                        connection.commit()
                    return redirect('/listReservasiRS/')
                except Exception as e:
                    e = str(e)
                    if ('duplicate key value violates unique constraint "reservasi_rs_pkey"' in e):
                        response['error'] = 'ID Pasien dan Tanggal Masuk telah terdaftar'
                    elif ('Tidak ada bed yang tersedia' in e):
                        response['error'] = 'Tidak ada bed yang tersedia pada RS dan Ruangan yang dipilih'
                    else :
                        response['error'] = 'Terjadi suatu kesalahan, silakan coba lagi nanti.'
    
    stmt1 = '''
    SELECT kode_faskes FROM RUMAH_SAKIT;
    '''
    kode_RS = tuple()
    try:
        with connection.cursor() as cursor:
            cursor.execute(stmt1)
            kode_RS = cursor.fetchall()
    except:
        pass

    stmt = '''
    SELECT nik FROM PASIEN;
    '''
    nik_pasien = tuple()
    try:
        with connection.cursor() as cursor:
            cursor.execute(stmt)
            nik_pasien = cursor.fetchall()
    except:
        pass

    response['listOfKodeRS'] = kode_RS
    response['listOfnik'] = nik_pasien
    form = ReservasiRSForm()
    response['form'] = form
    return render(request, 'app3/reservasiRS.html', response)

def data_basedOnKodeRS(request):
    if request.method == "POST":
        kode_RS = request.POST.get("kode_RS")

        list_items = []
        list_kode_ruangan = []
        list_kode_bed = []
        for kode in getKodeRuangan(kode_RS):
            list_kode_ruangan.append(kode[1]);
        
        for kode in getKodeBed(kode_RS):
            list_kode_bed.append(kode[1])
        
        item = {
            "list_kode_ruangan" : list_kode_ruangan,
            "list_kode_bed" : list_kode_bed
        }
        
    return JsonResponse(item)

def getKodeRuangan(kode_RS):
    stmt1 = '''
    SELECT koderuangan FROM RUANGAN_RS WHERE koders = %s ;
    '''
    with connection.cursor() as cursor:
        cursor.execute(stmt1, [kode_RS])
        kode_ruangan = cursor.fetchall()
    
    return [('', 'Kode Ruangan')] + [(kode[0], kode[0]) for kode in kode_ruangan]

def getKodeBed(kode_RS):
    stmt2 = '''
    SELECT kodebed FROM BED_RS WHERE koders = %s ;
    '''
    with connection.cursor() as cursor:
        cursor.execute(stmt2, [kode_RS])
        kode_bed = cursor.fetchall()

    return [('', 'Kode BED')] + [(kode[0], kode[0]) for kode in kode_bed]

def listReservasiRS(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_login)
    response = {}
    set_username(request, response)

    if (request.session.get('peran') not in ["admin_satgas", "pengguna_publik"]):
        response["peran_diizinkan"] = ["Admin Satgas", "Pengguna Publik"]
        return render(request, "app3/error.html", response)

    if (request.session.get('peran') in ["admin_satgas"]):
        stmt1 = '''
        SELECT * FROM RESERVASI_RS WHERE tglmasuk > %s;
        '''
        stmt2 = '''
        SELECT * FROM RESERVASI_RS WHERE tglmasuk <= %s;
        '''

        with connection.cursor() as cursor:
            cursor.execute(stmt1, [pd.to_datetime("today")])
            setOfReservasiRS = cursor.fetchall()
        
        with connection.cursor() as cursor:
            cursor.execute(stmt2, [pd.to_datetime("today")])
            ReservasiRSCantBeDeleted = cursor.fetchall()

    else:
        stmt1  = '''
        SELECT distinct R.kodepasien, R.tglmasuk, R.tglkeluar, R.koders, R.koderuangan, R.kodebed 
        FROM RESERVASI_RS R, PENGGUNA_PUBLIK PP, PASIEN P
        WHERE R.kodepasien = P.nik AND P.idpendaftar = %s;
        '''
        with connection.cursor() as cursor:
            cursor.execute(stmt1, [request.session.get('username')])
            setOfReservasiRS = cursor.fetchall()
        
        ReservasiRSCantBeDeleted = None    

    response['ReservasiRSCantBeDeleted'] = ReservasiRSCantBeDeleted
    response['setOfReservasiRS'] = setOfReservasiRS
    return render(request, 'app3/listReservasiRS.html', response)

def updateReservasiRS(request, kodepasien, tglMasuk):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_login)
    response = {}
    set_username(request, response)

    if (request.session.get('peran') not in ["admin_satgas"]):
        response["peran_diizinkan"] = ["Admin Satgas"]
        return render(request, "app3/error.html", response)

    stmt1 = '''
    SELECT * FROM RESERVASI_RS WHERE kodepasien = %s AND tglmasuk = %s;
    '''
    with connection.cursor() as cursor:
        cursor.execute(stmt1, [kodepasien, tglMasuk])
        reservasiRS = cursor.fetchall()

    form = ReservasiRSForm()

    form.fields["tglMasuk"].widget.attrs['disabled'] = True
    form.fields["tglMasuk"].initial = reservasiRS[0][1]
    form.fields["tglKeluar"].initial = reservasiRS[0][2]
    form.fields["kode_ruangan"].widget.attrs['disabled'] = True
    form.fields["kode_ruangan"].initial = reservasiRS[0][4]
    form.fields["kode_bed"].widget.attrs['disabled'] = True
    form.fields["kode_bed"].initial = reservasiRS[0][5]

    response['kodepasien'] = reservasiRS[0][0]
    response['koders'] = reservasiRS[0][3]

    response['dataReservasiRS'] = reservasiRS
    response['form'] = form
    return render (request, 'app3/updateReservasiRS.html', response)

def submitUpdateReservasiRS(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_login)
    response = {}
    set_username(request, response)

    if (request.session.get('peran') not in ["admin_satgas"]):
        response["peran_diizinkan"] = ["Admin Satgas"]
        return render(request, "app3/error.html", response)

    if(request.method == "POST"):
        form = ReservasiRSForm(request.POST)

        stmt1 = '''
        UPDATE RESERVASI_RS
        SET tglkeluar = %s WHERE kodepasien = %s AND tglmasuk = %s;
        '''
                
        kodepasien = request.POST.get('kodepasien')
        tglMasuk = request.POST.get('tglmasuk')
        tglKeluar = request.POST.get('tglkeluar')

        tglMasuk = pd.to_datetime(tglMasuk)
        tglKeluar = pd.to_datetime(tglKeluar)

        if (tglMasuk > tglKeluar):
            return redirect('/updateReservasiRS/'+ str(kodepasien) + '/' + str(tglMasuk) + '/')
            
        try:
            with connection.cursor() as cursor:
                cursor.execute(stmt1, [tglKeluar, kodepasien, tglMasuk])
                connection.commit()
                
        except:
            pass

    return redirect('/listReservasiRS/')

def deleteReservasiRS(request, kodepasien, tglMasuk):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_login)
    response = {}
    set_username(request, response)

    if (request.session.get('peran') not in ["admin_satgas"]):
        response["peran_diizinkan"] = ["Admin Satgas"]
        return render(request, "app3/error.html", response)

    if (request.method == 'POST'):
        stmt1 = '''
        DELETE FROM RESERVASI_RS WHERE kodepasien = %s AND tglmasuk = %s;
        '''
        try: 
            with connection.cursor() as cursor:
                cursor.execute(stmt1, [kodepasien, tglMasuk])
                connection.commit()
        except Exception as e:
            e = str(e)
            if ('violates foreign key constraint' in e):
                response['error'] = 'Reservasi RS tidak bisa dihapus karena ada atribut dari tabel lain yang menjadi foreign key dari Reservasi RS'
            else :
                response['error'] = 'Terjadi suatu kesalahan, silakan coba lagi nanti.'

    return redirect('/listReservasiRS/')
# RESERVASI RS

# JADWAL FASKES
def buatJadwalFaskes(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_login)
    response = {}
    set_username(request, response)

    if (request.session.get('peran') not in ["admin_satgas"]):
        response["peran_diizinkan"] = ["Admin Satgas"]
        return render(request, "app3/error.html", response)

    if ((request.method == 'POST')):
        form = JadwalFaskesForm(request.POST)
        
        if (form.is_valid()):
            # Ventilator harusnya ilang
            stmt1 = '''
            INSERT INTO jadwal(kode_faskes, shift, tanggal) VALUES (%s,%s,%s);

app3/templates/app3/detailFaskes.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app3/css/app3.css' %}">
<title> List Reservasi RS </title>
{%endblock style%}

{%block content%}
<section id="headerFaskes">
    <div class="headerFaskes">
    </div>
</section>
<section id="listJadwalFaskes" class="p-4">
    <div class="listJadwalFaskes">
        <div class="col">
            <div id="card-detail-faskes" class="card shadow">
                <div class="card-header">
                    <h4 class="font-weight-bold"> DATA FASILITAS KESEHATAN </h4>
                </div>
                <div class="card-body">
                    {% for tuple in setOfFaskes %}
                        <p> Kode Faskes: {{tuple.0}} </p>
                        <p> Tipe: {{tuple.1}} </p>
                        <p> Nama Faskes: {{tuple.2}} </p>
                        <p> Status Kepemilikan: {{tuple.3}} </p>
                        <p class="font-weight-bold"> Alamat: </p>
                        <p> Jalan: {{tuple.4}} </p>
                        <p> Kelurahan: {{tuple.5}} </p>
                        <p> Kecamatan: {{tuple.6}} </p>
                        <p> Kabupaten/Kota: {{tuple.7}} </p>
                        <p> Provinsi: {{tuple.8}} </p>
                    {%endfor%}
                </div>
                <a href="{% url 'app3:listFaskes' %}"> 
                    <button type="button" id="button-kembali" class="btn btn-secondary">Kembali</button>
                </a>
            </div>  
        </div>
    </div>
</section>
<script src="{% static 'app3/javascript/app3.js' %}" type="text/javascript"></script>
{% endblock content %}

app3/templates/app3/error.html
{% extends 'base.html' %}
{% load static %}
{%block style%}
<link rel="stylesheet" href="{% static 'app3/css/app3.css' %}">
<title>Error</title>
{%endblock style%}

{% block content %}
<section id="header">
    <div class="headerFaskes">
    </div>
</section>
<section id="error" class="p-4">
    <div class="listFaskes">
        <div class="d-flex justify-content-center align-items-center">
            <div class="card col-error">
                <p>Operasi hanya dapat dilakukan oleh: </p>
                {%if peran_diizinkan %}
                    {%for p in peran_diizinkan%}
                        <p> {{p}} </p>
                    {%endfor%}
                {%endif%}
            </div>
        </div>
    </div>
</section>
{% endblock content %}

app3/templates/app3/listFaskes.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app3/css/app3.css' %}">
<title> List Reservasi RS </title>
{%endblock style%}

{%block content%}
<section id="headerFaskes">
    <div class="headerFaskes">
    </div>
</section>
<section id="listJadwalFaskes" class="p-4">
    <div class="listJadwalFaskes">
      <div class="judulList">
        <h3>List Faskes</h3>
        <br>
      </div>
        <div class="d-flex justify-content-center align-items-center">
            <table class="table align-middle shadow p-3 mb-5 bg-white rounded">
                <thead>
                  <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Kode</th>
                    <th scope="col">Tipe</th>
                    <th scope="col">Nama</th>
                    <th>Update</th>
                    <th>Delete</th>
                    <th>Detail</th>
                  </tr>
                </thead>
                <tbody class="serial">
                    {% for tuple in setOfFaskes %}
                    <tr>
                        <td></td>
                        {% for attr in tuple %}
                            <td>{{attr}}</td>
                        {%endfor%}
                        <td>
                          <a href="{% url 'app3:updateFaskes' tuple.0 %}">
                            <button type="button" id="update" class="btn btn-secondary">Update</button>
                          </a>
                        </td>
                        <td>
                          <form action="{% url 'app3:deleteFaskes' tuple.0 %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" id="delete" class="btn btn-secondary">Delete</button>
                          </form>
                        </td>
                        <td>
                          <a href="{% url 'app3:detailFaskes' tuple.0 %}">
                            <button type="button" id="detail" class="btn btn-secondary">Detail</button>
                          </a>
                        </td>
                    </tr>
                  {%endfor%}
                </tbody>
              </table>
        </div>
        {% if error %}
            {{ error }}
        {% endif %}
        <a href="{% url 'app3:buatFaskes' %}"> 
            <button type="button" id="buat-jadwalFaskes" class="btn btn-secondary">Buat Faskes</button>
        </a>
    </div>
</section>
<script src="{% static 'app3/javascript/app3.js' %}" type="text/javascript"></script>
{% endblock content %}

app3/templates/app3/listJadwalFaskes.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app3/css/app3.css' %}">
<title> List Reservasi RS </title>
{%endblock style%}

{%block content%}
<section id="headerFaskes">
    <div class="headerFaskes">
    </div>
</section>
<section id="listJadwalFaskes" class="p-4">
    <div class="listJadwalFaskes">
        <div class="judulList">
            <h3>List Jadwal Faskes</h3>
            <br>
        </div>
        <div class="d-flex justify-content-center align-items-center">
            
            <table class="table align-middle shadow p-3 mb-5 bg-white rounded">
                <thead>
                  <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Faskes</th>
                    <th scope="col">Shift</th>
                    <th scope="col">Tanggal</th>
                  </tr>
                </thead>
                <tbody class="serial">
                    {% for tuple in setOfJadwalFaskes %}
                    <tr>
                        <td></td>
                        {% for attr in tuple %}
                            <td>{{attr}}</td>
                        {%endfor%}
                    </tr>
                  {%endfor%}
                </tbody>
              </table>
        </div>
        {% if error %}
          {{error}}
        {%endif%}
        <a href="{% url 'app3:buatJadwalFaskes' %}"> 
            <button type="button" id="buat-jadwalFaskes" class="btn btn-secondary">Buat Jadwal Faskes</button>
        </a>
    </div>
</section>
<script src="{% static 'app3/javascript/app3.js' %}" type="text/javascript"></script>
{% endblock content %}

app3/templates/app3/listReservasiRS.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app3/css/app3.css' %}">
<title> List Reservasi RS </title>
{%endblock style%}

{%block content%}
<section id="headerReservasiRS">
    <div class="headerReservasiRS">
    </div>
</section>
<section id="listReservasiRS" class="p-4">
    <div class="listReservasiRS">
        <div class="judulList">
            <h3>List Reservasi RS</h3>
            <br>
        </div>
        <div class="d-flex justify-content-center align-items-center">
            <table class="table align-middle shadow p-3 mb-5 bg-white rounded">
                <thead>
                  <tr>
                    <th scope="col">No.</th>
                    <th scope="col">NIK Pasien</th>
                    <th scope="col">Tanggal Masuk</th>
                    <th scope="col">Tanggal Keluar</th>
                    <th scope="col">Rumah Sakit</th>
                    <th scope="col">Ruangan</th>
                    <th scope="col">Bed</th>
                    {% if peran == 'admin_satgas' %}
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    {%endif%}
                  </tr>
                </thead>
                <tbody class="serial">
                    {% if peran == 'admin_satgas' %}
                        {% if ReservasiRSCantBeDeleted %}
                            {% for tuple in ReservasiRSCantBeDeleted %}
                            <tr>
                                <td></td>
                                <!-- Nanti yang ventilator dibuang -->
                                {% for attr in tuple %}
                                    <td>{{attr}}</td>
                                {%endfor%}
                                <td>
                                    <a href="{% url 'app3:updateReservasiRS' tuple.0 tuple.1%}">
                                        <button type="button" id="update" class="btn btn-secondary">Update</button>
                                    </a>
                                </td>
                            </tr>
                            {%endfor%}
                        {%endif%}
                        {% if setOfReservasiRS %}
                            {% for tuple in setOfReservasiRS %}
                            <tr>
                                <td></td>
                                <!-- Nanti yang ventilator dibuang -->
                                {% for attr in tuple %}
                                    <td>{{attr}}</td>
                                {%endfor%}
                                <td>
                                    <a href="{% url 'app3:updateReservasiRS' tuple.0 tuple.1%}">
                                        <button type="button" id="update" class="btn btn-secondary">Update</button>
                                    </a>
                                </td>
                                <td>
                                    <form action="{% url 'app3:deleteReservasiRS' tuple.0 tuple.1%}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" id="delete" class="btn btn-secondary">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            {%endfor%}  
                        {%endif%}
                    {%else%}
                        {% for tuple in setOfReservasiRS %}
                        <tr>
                            <td></td>
                            {% for attr in tuple %}
                                <td>{{attr}}</td>
                            {%endfor%}
                        </tr>
                        {%endfor%}  
                    {%endif%}
                </tbody>
              </table>
        </div>
        {% if peran == 'admin_satgas' %}
        <a href="{% url 'app3:reservasiRS' %}"> 
            <button type="button" id="buat-reservasiRS" class="btn btn-secondary">Buat Reservasi RS</button>
        </a>
        {%endif%}
    </div>
    {% if error %}
        {{error}}
    {%endif%}
</section>
<script src="{% static 'app3/javascript/app3.js' %}" type="text/javascript"></script>
{% endblock content %}

app3/templates/app3/listRumahSakit.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app3/css/app3.css' %}">
<title> List Rumah Sakit </title>
{%endblock style%}

{%block content%}
<section id="headerReservasiRS">
    <div class="headerReservasiRS">
    </div>
</section>
<section id="listReservasiRS" class="p-4">
    <div class="listReservasiRS">
        <div class="judulList">
            <h3>List Rumah Sakit</h3>
            <br>
        </div>
        <div class="d-flex justify-content-center align-items-center">
            <table class="table align-middle shadow p-3 mb-5 bg-white rounded">
                <thead>
                  <tr>
                    <th scope="col">Kode</th>
                    <th scope="col">Rujukan?</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                    {% for tuple in setOfRS %}
                    <tr>
                        <td>{{tuple.0}}</td>
                        <td>
                            {%if tuple.1 == '1'%}
                            <input id="checkbox" type="checkbox" disabled="disabled" checked="checked">
                            {%else%}
                            <input id="checkbox" type="checkbox" disabled="disabled">
                            {%endif%}
                        </td>
                        <td>
                            <a href="{% url 'app3:updateRS' tuple.0 %}">
                                <button type="button" id="update" class="btn btn-secondary">Update</button>
                            </a>
                        </td>
                    </tr>
                    {%endfor%}    
                </tbody>
              </table>
        </div>
        <a href="{% url 'app3:buatRS' %}"> 
            <button type="button" id="buat-reservasiRS" class="btn btn-secondary">Buat Rumah Sakit</button>
        </a>
    </div>
    {% if error %}
        {{error}}
    {%endif%}
</section>
<script src="{% static 'app3/javascript/app3.js' %}" type="text/javascript"></script>
{% endblock content %}

app3/templates/app3/listTransaksiRS.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app3/css/app3.css' %}">
<title> List Rumah Sakit </title>
{%endblock style%}

{%block content%}
<section id="headerReservasiRS">
    <div class="headerReservasiRS">
    </div>
</section>
<section id="listReservasiRS" class="p-4">
    <div class="listReservasiRS">
        <div class="judulList">
            <h3>List Transaksi RS</h3>
            <br>
        </div>
        <div class="d-flex justify-content-center align-items-center">
            <table class="table align-middle shadow p-3 mb-5 bg-white rounded">
                <thead>
                  <tr>
                    <th scope="col">Id Transaksi</th>
                    <th scope="col">Kode Pasien</th>
                    <th scope="col">Tanggal Pembayaran</th>
                    <th scope="col">Waktu Pembayaran</th>
                    <th scope="col">Tanggal Masuk</th>
                    <th scope="col">Total Biaya</th>
                    <th scope="col">Status Bayar</th>
                    <th scope="col">Update</th>
                    <th scope="col">Delete</th>
                  </tr>
                </thead>
                <tbody>
                    {% for tuple in setOfTransaksiRS %}
                    <tr>
                        <!-- Nanti yang ventilator dibuang -->
                        {% for attr in tuple %}
                            <td>{{attr}}</td>
                        {%endfor%}
                        <td>
                            <a href="{% url 'app3:updateTransaksiRS' tuple.0 %}">
                                <button type="button" id="update" class="btn btn-secondary">Update</button>
                            </a>
                        </td>
                        <td>
                            <form action="{% url 'app3:deleteTransaksiRS' tuple.0 %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" id="delete" class="btn btn-secondary">Delete</button>
                            </form>
                        </td>
                    </tr>
                    {%endfor%}      
                </tbody>
              </table>
        </div>
        {% if error %}
          {{error}}
        {%endif%}
    </div>
</section>
<script src="{% static 'app3/javascript/app3.js' %}" type="text/javascript"></script>
{% endblock content %}