app1/urls.py
from django.urls import re_path, path
from .views import *

app_name = 'app1'

urlpatterns = [
    path('logout/', logout, name='logout'),
    path('', homepage, name='homepage'),
    path('dashboard/', dashboard, name='dashboard'),
    path('login/', login, name='login'),
    path('registerAdminSistem/', registerAdminSistem, name='registerAdminSistem'),
    path('editAdminSistem/', editAdminSistem, name='editAdminSistem'),
    path('registerPenggunaPublik/', registerPenggunaPublik, name='registerPenggunaPublik'),
    path('editPenggunaPublik/', editPenggunaPublik, name='editPenggunaPublik'),
    path('registerDokter/', registerDokter, name='registerDokter'),
    path('editDokter/', editDokter, name='editDokter'),
    path('registerAdminSatgas/', registerAdminSatgas, name='registerAdminSatgas'),
    path('editAdminSatgas/', editAdminSatgas, name='editAdminSatgas'),
    path('listPasien/', listPasien, name='listPasien'),
    path('daftarPasien/', daftarPasien, name='daftarPasien'),
    path('updatePasien/<str:idPasien>/<str:namaPasien>', updatePasien, name='updatePasien'),
    path('detailPasien/<str:idPasien>', detailPasien, name='detailPasien'),
    path('deletePasien/<str:idPasien>', deletePasien, name='deletePasien'),
]

app3/urls.py
from django.urls import re_path, path
from .views import *

app_name = 'app3'

urlpatterns = [
    path('reservasiRS/', reservasiRS, name='reservasiRS'),
    path('data/BasedOnKodeRS/', data_basedOnKodeRS, name='data_basedOnKodeRS'),
    path('listReservasiRS/', listReservasiRS, name='listReservasiRS'),
    path('updateReservasiRS/<str:kodepasien>/<str:tglMasuk>/', updateReservasiRS, name='updateReservasiRS'),
    path('submitUpdateReservasiRS/', submitUpdateReservasiRS, name='submitUpdateReservasiRS'),
    path('deleteReservasiRS/<str:kodepasien>/<str:tglMasuk>/', deleteReservasiRS, name='deleteReservasiRS'),

    path('buatJadwalFaskes/', buatJadwalFaskes, name='buatJadwalFaskes'),
    path('listJadwalFaskes/', listJadwalFaskes, name='listJadwalFaskes'),

    path('buatRS/', buatRS, name='buatRS'),
    path('listRumahSakit/', listRumahSakit, name='listRumahSakit'),
    path('updateRS/<str:kode_faskes>/', updateRS, name='updateRS'),
    path('submitUpdateRS/', submitUpdateRS, name='submitUpdateRS'),

    path('listTransaksiRS/', listTransaksiRS, name='listTransaksiRS'),
    path('updateTransaksiRS/<str:id_transaksi>/', updateTransaksiRS, name='updateTransaksiRS'),
    path('submitTransaksiRS/', submitTransaksiRS, name='submitTransaksiRS'),
    path('deleteTransaksiRS/<str:id_transaksi>/', deleteTransaksiRS, name='deleteTransaksiRS'),

    path('buatFaskes/', buatFaskes, name='buatFaskes'),
    path('listFaskes/', listFaskes, name='listFaskes'),
    path('updateFaskes/<str:kode>/', updateFaskes, name='updateFaskes'),
    path('submitFaskes/', submitFaskes, name='submitFaskes'),
    path('deleteFaskes/<str:kode>/', deleteFaskes, name='deleteFaskes'),
    path('detailFaskes/<str:kode>/', detailFaskes, name='detailFaskes'),
]

tk4_kelompok8_basdat/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('app1.urls')),
    path('', include('app2.urls')),
    path('', include('app3.urls')),
    path('', include('app4.urls')),
    path('', include('app5.urls')),
]

app1/views.py
from django.shortcuts import render, redirect
from django.db import connection
from django.shortcuts import render
from .forms import *
from django.http import JsonResponse, Http404

url_dashboard = 'app1:dashboard'
url_login = 'app1:login'
url_listPasien = 'app1:listPasien'

def set_username(request, response):
    response['is_authenticated'] = request.session.get('is_authenticated')
    response['username'] = request.session.get('username')
    response['peran'] = request.session.get('peran')

def dashboard(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_login)
    response = {}
    set_username(request, response)
    return render(request, 'app1/dashboard.html', response)

def homepage(request):
    if (request.session.get('is_authenticated')):
        return redirect(url_dashboard)
    response = {}
    set_username(request, response)
    return render(request, 'app1/homepage.html', response)

def login(request):
    if (request.session.get('is_authenticated')):
        return redirect(url_dashboard)
    response = {}

    if (request.method == 'POST'):
        form = LoginForm(request.POST)
        if form.is_valid():
            stmt = '''
            SELECT * FROM akun_pengguna WHERE username=%s AND PASSWORD=%s;
            '''
            try:
                user = tuple()
                with connection.cursor() as cursor:
                    cursor.execute(stmt, [form.cleaned_data['email'], form.cleaned_data['password']])
                    user = cursor.fetchone()
                request.session['username'] = user[0]
                request.session['peran'] = user[2]
                request.session['is_authenticated'] = True
                return redirect(url_dashboard)
            except:
                response['error'] = 'Email atau password salah, silakan coba lagi'

    form = LoginForm(request.POST)
    response['form'] = form
    return render(request, 'app1/login.html', response)

def logout(request):
    request.session.flush()
    return redirect(url_login)

def registerAdminSistem(request):
    if (request.session.get('is_authenticated')):
        return redirect(url_dashboard)
    peran = 'admin'
    response = {}

    if (request.method == 'POST'):
        form = RegisterAdminSistemForm(request.POST)    
        if (form.is_valid()):
            stmt1 = '''
            INSERT INTO akun_pengguna(username, password, peran) VALUES (%s,%s,%s);
            '''

            stmt2 = '''
            INSERT INTO admin(username) VALUES (%s);
            '''
            try:
                with connection.cursor() as cursor:
                    cursor.execute(stmt1, [form.cleaned_data['email'], form.cleaned_data['password'], peran])
                    connection.commit()
                with connection.cursor() as cursor:
                    cursor.execute(stmt2, [form.cleaned_data['email']])
                    connection.commit()
                
                request.session['username'] = form.cleaned_data['email']
                request.session['peran'] = peran
                request.session['is_authenticated'] = True
                return redirect(url_dashboard)
            except Exception as e:
                e = str(e)
                if ('already exists' in e):
                    response['error'] = 'Email telah digunakan, silakan gunakan email lain'
                elif ('Password harus memiliki minimal satu huruf kapital dan satu angka.' in e):
                    response['error'] = 'Password Anda belum memenuhi syarat, silahkan pastikan bahwa password minimal terdapat 1 huruf kapital dan 1 angka'

    registerAdminSistemForm = RegisterAdminSistemForm(request.POST)
    response['form'] = registerAdminSistemForm
    response['register_peran'] = 'Admin Sistem'

    return render(request, 'app1/register.html', response)

def editAdminSistem(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_dashboard)
    response = {}
    peran = 'admin'
    if (peran != request.session.get('peran')):
        raise Http404
    set_username(request, response)

    if (request.method == 'POST'):
        data = request.POST.copy()
        data['email'] = request.session.get('username')
        form = EditAdminSistemForm(data)
        if (form.is_valid()):
            stmt = '''
            UPDATE akun_pengguna
            SET password=%s
            WHERE username=%s;
            '''
            try:
                with connection.cursor() as cursor:
                    cursor.execute(stmt, [form.cleaned_data['password'], form.cleaned_data['email']])
                    connection.commit()
                    
                return redirect(url_dashboard)
            except Exception as e:
                e = str(e)
                if ('Password harus memiliki minimal satu huruf kapital dan satu angka.' in e):
                    response['error'] = 'Password Anda belum memenuhi syarat, silahkan pastikan bahwa password minimal terdapat 1 huruf kapital dan 1 angka'

    response['form'] = EditAdminSistemForm(initial = {'email': 'email: ' + request.session.get("username")})
    return render(request, 'app1/editProfil.html', response)

def registerPenggunaPublik(request):
    if (request.session.get('is_authenticated')):
        return redirect(url_dashboard)
    peran = 'pengguna_publik'
    response = {}

    if (request.method == 'POST'):
        form = RegisterPenggunaPublikForm(request.POST)
        if (form.is_valid()):
            stmt1 = '''
            INSERT INTO akun_pengguna(username, password, peran) VALUES (%s,%s,%s);
            '''
            stmt2 = '''
            INSERT INTO pengguna_publik(username, nik, nama, status, peran, nohp) VALUES (%s, %s, %s, %s, %s, %s);
            '''
            try:
                with connection.cursor() as cursor:
                    cursor.execute(stmt1, [form.cleaned_data['email'], form.cleaned_data['password'], peran])
                    connection.commit()
                with connection.cursor() as cursor:
                    cursor.execute(stmt2, [
                        form.cleaned_data['email'],
                        form.cleaned_data['nik'],
                        form.cleaned_data['nama'],
                        'AKTIF',
                        'penanggung jawab',
                        form.cleaned_data['nohp']
                    ])
                    connection.commit()
                
                request.session['username'] = form.cleaned_data['email']
                request.session['peran'] = peran
                request.session['is_authenticated'] = True
                return redirect(url_dashboard)
            except Exception as e:
                e = str(e)
                if ('already exists' in e):
                    response['error'] = 'Email telah digunakan, silakan gunakan email lain'
                elif ('Password harus memiliki minimal satu huruf kapital dan satu angka.' in e):
                    response['error'] = 'Password Anda belum memenuhi syarat, silahkan pastikan bahwa password minimal terdapat 1 huruf kapital dan 1 angka'

    registerPenggunaPublikForm = RegisterPenggunaPublikForm(request.POST)
    response['form'] = registerPenggunaPublikForm
    response['register_peran'] = 'Pengguna Publik'

    return render(request, 'app1/register.html', response)

def editPenggunaPublik(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect(url_dashboard)
    response = {}
    peran = 'pengguna_publik'
    if (peran != request.session.get('peran')):
        raise Http404
    set_username(request, response)

    if (request.method == 'POST'):
        data = request.POST.copy()
        data['email'] = request.session.get('username')
        form = EditPenggunaPublikForm(data)
        if (form.is_valid()):
            stmt1 = '''
            UPDATE akun_pengguna
            SET password=%s
            WHERE username=%s;
            '''
            stmt2 = '''
            UPDATE pengguna_publik
            SET
                nama=%s,
                nik=%s,
                nohp=%s
            WHERE username=%s;
            '''
            try:
                with connection.cursor() as cursor:
                    cursor.execute(stmt1, [form.cleaned_data['password'], form.cleaned_data['email']])
                    connection.commit()
                with connection.cursor() as cursor:
                    cursor.execute(stmt2, [form.cleaned_data['nama'], form.cleaned_data['nik'], form.cleaned_data['nohp'], form.cleaned_data['email']])
                    connection.commit()
                return redirect(url_dashboard)
            except Exception as e:
                e = str(e)
                if ('Password harus memiliki minimal satu huruf kapital dan satu angka.' in e):
                    response['error'] = 'Password Anda belum memenuhi syarat, silahkan pastikan bahwa password minimal terdapat 1 huruf kapital dan 1 angka'

    data = {'email': 'email: ' + request.session.get("username")}
    stmt = '''
    SELECT nama, nik, nohp
    FROM pengguna_publik
    WHERE username=%s;
    '''
    try:
        with connection.cursor() as cursor:
            cursor.execute(stmt, [request.session.get('username')])
            ret = cursor.fetchone()
            data['nama'] = ret[0]
            data['nik'] = ret[1]
            data['nohp'] = ret[2]
    except:
        pass
    response['form'] = EditPenggunaPublikForm(initial=data)
    return render(request, 'app1/editProfil.html', response)

def registerDokter(request):
    if (request.session.get('is_authenticated')):
        return redirect(url_dashboard)
    peran = 'dokter'
    response = {}

    if (request.method == 'POST'):
        form = RegisterDokterForm(request.POST)
        if (form.is_valid()):
            stmt1 = '''
            INSERT INTO akun_pengguna(username, password, peran) VALUES (%s,%s,%s);
            '''

app1/templates/app1/daftarPasien.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> Daftar Pasien </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="daftarPasien" class="p-4">
    <div class="daftarPasien">
        <div class="d-flex justify-content-center">
            <div class="card card-pasien">
                <div class="card-header">
                    <h3>Form Pendaftaran Pasien</h3>
                </div>
                <div class="card-body">
                    <form method="POST">
                        <div class="form-group">
                            {% csrf_token %}
                            {%for field in form%}
                                <p> {{field}} </p>
                            {%endfor%}
                        </div>
                        <button id="submit" class="btn btn-primary intabel" method="POST">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

app1/templates/app1/detailPasien.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> List Fasilitas Kesehatan </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="listPasien" class="p-4">
    <div class="listPasien">
        <div class="d-flex justify-content-center align-items-center">
            <table class="table align-middle shadow p-3 mb-5 bg-white rounded">
                <tbody>
                <tr>
                    <td>Pendaftar:</td>
                    <td> {{pendaftar}} </td>
                </tr>
                <tr>
                    <td>NIK:</td>
                    <td> {{nik}} </td>
                </tr>
                <tr>
                    <td>Nama</td>
                    <td> {{nama}} </td>
                </tr>
                <tr>
                    <td>Nomor Telepon</td>
                    <td> {{notelp}} </td>
                </tr>
                <tr>
                    <td>Nomor Hp</td>
                    <td> {{nohp}} </td>
                </tr> 
                <tr><td></td><td></td></tr>
                <tr>
                    <td>Alamat (Sesuai KTP):</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Jalan</td>
                    <td> {{kjalan}} </td>
                </tr>
                <tr>
                    <td>Kelurahan</td>
                    <td> {{kkelurahan}} </td>
                </tr>
                <tr>
                    <td>Kecamatan</td>
                    <td> {{kkecamatan}} </td>
                </tr>
                <tr>
                    <td>Kabupaten/Kota</td>
                    <td> {{kkabkot}} </td>
                </tr>
                <tr>
                    <td>Provinsi</td>
                    <td> {{kprov}} </td>
                </tr>
                <tr><td></td><td></td></tr>
                <tr>
                    <td>Alamat (Domisili)</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Jalan</td>
                    <td> {{djalan}} </td>
                </tr>
                <tr>
                    <td>Kelurahan</td>
                    <td> {{dkelurahan}} </td>
                </tr>
                <tr>
                    <td>Kecamatan</td>
                    <td> {{dkecamatan}} </td>
                </tr>
                <tr>
                    <td>Kabupaten/Kota</td>
                    <td> {{dkabkot}} </td>
                </tr>
                <tr>
                    <td>Provinsi</td>
                    <td> {{dprov}} </td>
                </tr>                   
                </tbody>
              </table>
        </div>
        <a href="{% url 'app1:listPasien' %}"> 
            <button type="button" id="daftar-pasien" class="btn btn-secondary">Kembali</button>
        </a>
    </div>
</section>
{% endblock content %}

app1/templates/app1/editProfil.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> Ubah Profil </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="daftarPasien" class="p-4">
    <div class="daftarPasien">
        <div class="d-flex justify-content-center">
            <div class="card card-pasien">
                <div class="card-header">
                    <h3>Ubah Profil</h3>
                </div>
                {% if error %}
                <p class="error">{{ error }}</p>
                {% endif %}
                <div class="card-body">
                    <form method="POST">
                        <div class="form-group">
                            {% csrf_token %}
                            {%for field in form%}
                                <p> {{field}} </p>
                            {%endfor%}
                        </div>
                        <button id="submit" class="btn btn-primary intabel" method="POST">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

app1/templates/app1/homepage.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> Homepage </title>
{%endblock style%}

{% block content %}
<!-- Jumbotron -->
<section>
    <div class="p-5 bg-image rounded-3">
        <div class="d-flex justify-content-left align-items-center h-100">
            <div class="text-white">
            <h1 id="siruco-title" class="font-weight-bold">SIRUCO</h1>
            <h4 class="font-weight-light">Your Health is Our Priority</h4>
            <hr/>
            <a href="#aboutus">
                <button id="button-learn-more" type="button" class="mt-5 btn btn-light">Learn More</button>
            </a>
            </div>
        </div>
    </div>
</section>
<!-- Jumbotron -->

<section id="aboutus" class="p-4 mb-4 mt-4">
    <div id=card-about-us" class="card-group">
        <div class="card 10 p-3">
            <img id="admin" class="card-img-top" src="{% static 'app1/img/admin.png' %}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Responsive</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
        </div>
        <div class="card 10 p-3">
            <img id="hospital" class="card-img-top" src="{% static 'app1/img/hospital.png' %}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Best Service</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
        </div>
        <div class="card 10 p-3">
            <img id="stethoscope" class="card-img-top" src="{% static 'app1/img/stethoscope.png' %}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Qualified Doctor</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
        </div>
    </div>
</section>

<!--Pilihan-->
<section id="pilihan-navigasi" class="p-4">
    <div class="row justify-content-center align-items-center mt-5">
        <h1 id="judul-servis" class="font-weight-normal ">Dedicated to provide categories of service</h1>
        <p>This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4 mb-5">
        <div class="col mt-5">
            <a href="{% url 'app1:listPasien' %}">
                <img src="{% static 'app1/img/Pasien.png' %}" class="card-img" alt="..."/>
                <div class="centered">Pasien</div>
            </a>
        </div>
        <div class="col mt-5">
            <a href="{% url 'app3:listFaskes' %}">
                <img src="{% static 'app1/img/FasilitasKesehatan.png' %}" class="card-img" alt="..."/>
                <div class="centered">Fasilitas Kesehatan</div>
            </a>
        </div>
        <div class="col mt-5">
            <a href="">
                <img src="{% static 'app1/img/RumahSakit.png' %}" class="card-img" alt="..."/>
                <div class="centered">Rumah Sakit</div>
            </a>
        </div>
        <div class="col mt-5">
            <a href="">
                <img src="{% static 'app1/img/Hotel.png' %}" class="card-img" alt="..."/>
                <div class="centered">Hotel</div>
            </a>
        </div>
        <div class="col mt-5">
            <a href="">
                <img src="{% static 'app1/img/Transaksi.png' %}" class="card-img" alt="..."/>
                <div class="centered">Transaksi</div>
            </a>
        </div>

    </div>
</section>

{% endblock content %}

app1/templates/app1/listPasien.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> List Fasilitas Kesehatan </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="listPasien" class="p-4">
    <div class="listPasien">
        <div class="d-flex justify-content-center align-items-center">
            <table class="table align-middle shadow p-3 mb-5 bg-white rounded">
                <thead>
                  <tr>
                    <th scope="col">No.</th>
                    <th scope="col">NIK</th>
                    <th scope="col">Nama Pasien</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                    {%for a,b in pasien%}
                  <tr>
                    <td> {{a}} </td>
                    <td> {{b}} </td>
                    <td>
                      <a href="{% url 'app1:updatePasien' idPasien=a namaPasien=b %}">
                      <button type="button" id="update" class="btn btn-secondary">Update</button>
                    </td>
                    <td>
                      <a href="{% url 'app1:deletePasien' idPasien=a %}">
                        <button type="button" id="delete" class="btn btn-secondary">Delete</button>
                    </td>
                    <td>
                        <a href="{% url 'app1:detailPasien' idPasien=a %}">
                        <button type="button" id="detail" class="btn btn-secondary" method="GET">Detail</button>
                    </td>
                  </tr>
                  {%endfor%}
                  <script>
                    var tables = document.getElementsByTagName('tbody')
                    var table = tables[tables.length - 1];
                    var rows = table.rows;
                    for(var i = 0, td; i < rows.length; i++){
                        td = document.createElement('td');
                        td.appendChild(document.createTextNode(i + 1));
                        rows[i].insertBefore(td, rows[i].firstChild);
                    }
                </script>
                </tbody>
              </table>
        </div>
        <a href="{% url 'app1:daftarPasien' %}"> 
            <button type="button" id="daftar-pasien" class="btn btn-secondary">Daftarkan Pasien!</button>
        </a>
    </div>
</section>
{% endblock content %}

app1/templates/app1/login.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> Login Page </title>
{%endblock style%}

{%block content%}
<section id="login" class="p-4">
    <div class="login">
        <div class="d-flex justify-content-center">
            <div class="card card-login">
                <div class="card-header">
                    <h3>Sign In</h3>
                </div>
                {% if error %}
                <div class="error">{{ error }}</div>
                {% endif %}
                <div class="card-body">
                    <form method="POST">
                        <div class="inputform">
                            {% csrf_token %}
                            {%for field in form%}
                                <p> {{field}} </p>
                            {%endfor%}
                        </div>
                        <button id="login-submit" class="btn btn-primary intabel" method="POST">Log In</button>
                    </form>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-center links">
                        Don't have an account?
                        <a id="register-text" href="{% url 'app1:registerAdminSistem'%}">Register</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

app1/templates/app1/register.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> Register Page </title>
{%endblock style%}

{%block content%}
<section id="register" class="p-4">
    <div class="register">
      <div class="d-flex justify-content-center">
        <div class="card h-100 card-register">

            <div class="btn-group" role="group" aria-label="Basic example">
              <a href="{% url 'app1:registerAdminSistem'%}">
                <button type="button" class="pilih-role btn btn-secondary">Admin Sistem</button>
              </a>
              <a href="{% url 'app1:registerPenggunaPublik'%}">
                <button type="button" class="pilih-role btn btn-secondary">Pengguna Publik</button>
              </a>
              <a href="{% url 'app1:registerDokter'%}">
                <button type="button" class="pilih-role btn btn-secondary">Dokter</button>
              </a>
              <a href="{% url 'app1:registerAdminSatgas'%}">
                <button type="button" class="pilih-role btn btn-secondary">Admin Satgas</button>
              </a>
            </div>

            <div class="card-header">
                <h3>Register {{ register_peran }}</h3>
            </div>
            {% if error %}
            <div class="error">{{ error }}</div>
            {% endif %}
            <div class="card-body">
              <form method="POST">
                <div class="inputform">
                    {% csrf_token %}
                    {%for field in form%}
                        <p> {{field}} </p>
                    {%endfor%}
                </div>
                <button id="register-submit" class="btn btn-primary intabel" method="POST">Register</button>
              </form>
            </div>

        </div>
      </div>

    </div>
</section>
{% endblock content %}

app1/templates/app1/updatePasien.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}">
<title> Daftar Pasien </title>
{%endblock style%}

{%block content%}
<section id="header">
    <div class="headerPasien">
    </div>
</section>
<section id="daftarPasien" class="p-4">
    <div class="daftarPasien">
        <div class="d-flex justify-content-center">
            <div class="card card-pasien">
                {% if 'pengguna_publik' == peran %}
                <div class="card-header">
                    <h3>Form Update Pendaftaran Pasien</h3>
                </div>
                <div class="card-body">
                    <form method="POST">
                        <div class="form-group">
                            {% csrf_token %}
                            {%for field in form%}
                                <p> {{field}} </p>
                            {%endfor%}
                        </div>
                        <button id="submit" class="btn btn-primary intabel" method="POST">Simpan</button>
                    </form>
                </div>
                {% else %}
                <div class="card-header">
                    <h3>Anda tidak dapat mengakses halaman ini</h3>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}